name: ChunkManager
main: thulinma.chunkmanager.ChunkManager
version: 0.4.1
description: Improves the vanilla CraftBukkit chunk sending algorithms, as well as providing more control over chunk sending.
authors: [Thulinma]
